# Site Data
title: The Fifth Corner - Portfolio & Devlog
description: All about my game development challenges, programming insights, and creative projects.
image: /assets/images/default-preview-image.png
url: https://theby.github.io
baseurl: ""

# Configuration
remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
google_analytics: G-M7HRV5WG9L
show_downloads: false
show_navigation: true
permalink: /blog/:title/
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      category: blog
      seo:
        type: BlogPosting
feed:
  posts_limit: 10
  path: /blog/feed.xml
  icon: /assets/images/favicons/website-icon-32x32.png
  logo: /assets/images/favicons/website-icon-32x32.png

# Giscus - https://giscus.app
giscus:
  enabled: true
  repo: "Theby/theby.github.io"
  repo_id: "R_kgDOQYKm0A"
  category: "General"
  category_id: "DIC_kwDOQYKm0M4CzeYc"
  mapping: url
  strict: 0
  reactions_enabled: 1
  emit_metadata: 1
  input_position: top
  theme: dark
  lang: en
  loading: lazy

# Profile
author: 
  name: Esteban Gaete Flores
  nickname: Tebi
  title: Senior Unity Game Developer
  description: Gameplay & Tools Engineer with 10+ years creating fast, clean systems, responsive gameplay, and tools that boost team efficiency.
socials:
  - name: cv
    url: /resume
    inTab: true
  - name: linkedin
    url: https://www.linkedin.com/in/estebangaeteflores
  - name: github
    url: https://github.com/Theby

# jekyll-seo-tag
social:
  name: Esteban Gaete Flores
  links:
    - https://www.linkedin.com/in/estebangaeteflores
    - https://github.com/Theby
    - https://x.com/TebiFestival
    - https://bsky.app/profile/tebisight.bsky.social

# Coffe
support_me:
  name: Buy me a Coffe! ☕︎
  url: https://buymeacoffe.com
  show: false

# Contact
chat_platforms:
    - name: x
      url: https://x.com/TebiFestival
      handler: TebiFestival
    - name: bluesky
      url: https://bsky.app/profile/tebisight.bsky.social
      handler: tebisight.bsky.social
    - name: linkedin
      url: https://www.linkedin.com/in/estebangaeteflores/
      handler: in/estebangaeteflores/
    - name: discord
      handler: tebifestival